boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_handler_asm.o: interrupt_handler_asm.S
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
interrupt_handler.o: interrupt_handler.c interrupt_handler.h lib.h \
  types.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h
keyboard.o: keyboard.c keyboard.h
lib.o: lib.c lib.h types.h
