boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_handler_asm.o: interrupt_handler_asm.S
paging_asm.o: paging_asm.S
syscalls_linkage.o: syscalls_linkage.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h types.h lib.h devices/rtc.h \
  types.h syscalls.h devices/rtc.h devices/keyboard.h devices/scancodes.h \
  types.h x86_desc.h paging.h
interrupt_handler.o: interrupt_handler.c interrupt_handler.h lib.h \
  types.h devices/rtc.h types.h devices/i8259.h devices/keyboard.h \
  devices/scancodes.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h devices/i8259.h \
  types.h debug.h devices/rtc.h paging.h devices/keyboard.h \
  devices/scancodes.h filesystem.h
lib.o: lib.c lib.h types.h devices/keyboard.h devices/scancodes.h types.h
paging.o: paging.c paging.h lib.h types.h
scheduling.o: scheduling.c scheduling.h filesystem.h types.h syscalls.h \
  lib.h devices/rtc.h types.h devices/keyboard.h devices/scancodes.h \
  x86_desc.h paging.h
syscalls.o: syscalls.c syscalls.h lib.h types.h devices/rtc.h types.h \
  filesystem.h devices/keyboard.h devices/scancodes.h x86_desc.h paging.h \
  scheduling.h
i8259.o: devices/i8259.c devices/i8259.h types.h lib.h types.h
keyboard.o: devices/keyboard.c devices/keyboard.h devices/scancodes.h \
  types.h lib.h types.h devices/i8259.h filesystem.h
ps2.o: devices/ps2.c devices/ps2.h lib.h types.h
rtc.o: devices/rtc.c devices/rtc.h types.h lib.h types.h devices/i8259.h
scancodes.o: devices/scancodes.c devices/scancodes.h types.h lib.h \
  types.h
spinlocks.o: synchronization/spinlocks.c synchronization/spinlocks.h \
  types.h lib.h types.h
