boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_handler_asm.o: interrupt_handler_asm.S
paging_asm.o: paging_asm.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h types.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
interrupt_handler.o: interrupt_handler.c interrupt_handler.h lib.h \
  types.h rtc.h i8259.h keyboard.h scancodes.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  rtc.h paging.h keyboard.h scancodes.h filesystem.h
keyboard.o: keyboard.c keyboard.h scancodes.h types.h lib.h i8259.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h lib.h types.h
ps2.o: ps2.c ps2.h lib.h types.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h
scancodes.o: scancodes.c scancodes.h types.h lib.h
